### ISSUE TITLE
No such file or directory: './osod/ckpt/baseline/19_basemln.json'

### ISSUE THREAD

**Issue by Wenqi-Ge** [jeongeun980906/ITHOR_Navi#3]
Thanks for your great work! 
but when I try to run SPL2.py and DEMO3.ipynb
it occurs error `
No such file or directory: './osod/ckpt/baseline/19_basemln.json'
`
i find it in `fast_rcnn_mln.py` 
```
if cfg.MODEL.ROI_HEADS.UNCT:
            self.path = '{}/ckpt/baseline/{}_{}.json'.format(cfg.PATH,cfg.MODEL.SAVE_IDX,MODEL_NAME)
        else:
            self.path = None
```
I wonder how can I get the file, may you give me some help? thanks a lot :D

**Comment by jeongeun980906** [comment]
Sorry for the inconvenience. We have updated the google drive! 

Thank you

**Comment by Wenqi-Ge** [comment]
It works! Thanks a lot🌹
